/**
 * Tests for SettingsStore.upsertOnboardingMilestone (PR110b).
 *
 * Verifies the write path:
 *  - timestamp is generated by the store (never accepted from caller)
 *  - invalid id surfaces an error (via the sanitizer's closed enum)
 *  - last-valid-entry-wins dedup with stable first-seen position
 *  - settings.json round-trips through the sanitizer on read
 *  - upserting one milestone never disturbs other milestones
 */

import { strict as assert } from 'node:assert';
import { describe, it } from 'node:test';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { createSettingsStore } from '../settings-store.js';

describe('SettingsStore.upsertOnboardingMilestone (PR110b)', () => {
  it('stamps a fresh Date.now() timestamp (renderer cannot tamper)', async () => {
    const workspaceRoot = await mkdtemp(join(tmpdir(), 'maka-settings-milestone-'));
    try {
      const store = createSettingsStore(workspaceRoot);
      const before = Date.now();
      const result = await store.upsertOnboardingMilestone('first_chat_sent', 'completed');
      const after = Date.now();
      assert.equal(result.length, 1);
      const entry = result[0];
      assert.ok(entry);
      assert.equal(entry.id, 'first_chat_sent');
      assert.ok(typeof entry.completedAt === 'number');
      assert.ok(
        entry.completedAt! >= before && entry.completedAt! <= after,
        'timestamp must come from main process clock',
      );
    } finally {
      await rm(workspaceRoot, { recursive: true, force: true });
    }
  });

  it('skipped status writes skippedAt (mutually exclusive with completedAt)', async () => {
    const workspaceRoot = await mkdtemp(join(tmpdir(), 'maka-settings-milestone-skipped-'));
    try {
      const store = createSettingsStore(workspaceRoot);
      const result = await store.upsertOnboardingMilestone('first_personalization', 'skipped');
      const entry = result[0];
      assert.ok(entry);
      assert.equal(entry.id, 'first_personalization');
      assert.ok(typeof entry.skippedAt === 'number');
      assert.equal(entry.completedAt, undefined);
    } finally {
      await rm(workspaceRoot, { recursive: true, force: true });
    }
  });

  it('rejects invalid status (TypeScript-bypassing call)', async () => {
    const workspaceRoot = await mkdtemp(join(tmpdir(), 'maka-settings-milestone-invalid-'));
    try {
      const store = createSettingsStore(workspaceRoot);
      // Cast to bypass TS so we can prove the runtime guard works.
      // Keep the receiver via arrow fn so `this` isn't lost.
      await assert.rejects(
        () =>
          (
            store.upsertOnboardingMilestone as unknown as (
              id: string,
              status: string,
            ) => Promise<unknown>
          ).call(store, 'first_chat_sent', 'unknown_status'),
        /invalid onboarding milestone status/,
      );
    } finally {
      await rm(workspaceRoot, { recursive: true, force: true });
    }
  });

  it('rejects invalid milestone id (sanitizer drops, then store re-throws)', async () => {
    const workspaceRoot = await mkdtemp(join(tmpdir(), 'maka-settings-milestone-bad-id-'));
    try {
      const store = createSettingsStore(workspaceRoot);
      await assert.rejects(
        () =>
          (
            store.upsertOnboardingMilestone as unknown as (
              id: string,
              status: 'completed' | 'skipped',
            ) => Promise<unknown>
          ).call(store, 'not_a_milestone', 'completed'),
        /invalid onboarding milestone id/,
      );
    } finally {
      await rm(workspaceRoot, { recursive: true, force: true });
    }
  });

  it('upserting the same id last-valid-entry wins (skipped overrides completed)', async () => {
    const workspaceRoot = await mkdtemp(join(tmpdir(), 'maka-settings-milestone-upsert-'));
    try {
      const store = createSettingsStore(workspaceRoot);
      await store.upsertOnboardingMilestone('first_chat_sent', 'completed');
      const after = await store.upsertOnboardingMilestone('first_chat_sent', 'skipped');
      assert.equal(after.length, 1);
      const entry = after[0];
      assert.equal(entry?.id, 'first_chat_sent');
      assert.ok(typeof entry?.skippedAt === 'number');
      // Once skipped is set, completed must NOT survive.
      assert.equal(entry?.completedAt, undefined);
    } finally {
      await rm(workspaceRoot, { recursive: true, force: true });
    }
  });

  it('does not disturb other milestones when upserting one', async () => {
    const workspaceRoot = await mkdtemp(join(tmpdir(), 'maka-settings-milestone-others-'));
    try {
      const store = createSettingsStore(workspaceRoot);
      await store.upsertOnboardingMilestone('first_chat_sent', 'completed');
      const before = (await store.get()).onboarding.milestones[0]?.completedAt;
      await store.upsertOnboardingMilestone('first_personalization', 'completed');
      const after = (await store.get()).onboarding.milestones;
      assert.equal(after.length, 2);
      const chat = after.find((m) => m.id === 'first_chat_sent');
      const pers = after.find((m) => m.id === 'first_personalization');
      assert.equal(chat?.completedAt, before, 'first_chat_sent timestamp preserved');
      assert.ok(pers?.completedAt);
    } finally {
      await rm(workspaceRoot, { recursive: true, force: true });
    }
  });

  it('settings.json on disk contains only sanitized milestones', async () => {
    const workspaceRoot = await mkdtemp(join(tmpdir(), 'maka-settings-milestone-disk-'));
    try {
      const store = createSettingsStore(workspaceRoot);
      await store.upsertOnboardingMilestone('first_chat_sent', 'completed');
      const raw = await readFile(join(workspaceRoot, 'settings.json'), 'utf8');
      const parsed = JSON.parse(raw) as {
        onboarding: { milestones: Array<Record<string, unknown>> };
      };
      assert.equal(parsed.onboarding.milestones.length, 1);
      const entry = parsed.onboarding.milestones[0]!;
      // Must contain only the schema fields — nothing else.
      assert.deepEqual(Object.keys(entry).sort(), ['completedAt', 'id']);
    } finally {
      await rm(workspaceRoot, { recursive: true, force: true });
    }
  });

  it('reading settings.json with garbage milestones drops them via sanitizer', async () => {
    const workspaceRoot = await mkdtemp(join(tmpdir(), 'maka-settings-milestone-garbage-'));
    try {
      const store = createSettingsStore(workspaceRoot);
      // Seed a bad settings.json by hand and reload.
      const { writeFile, mkdir } = await import('node:fs/promises');
      await mkdir(workspaceRoot, { recursive: true });
      await writeFile(
        join(workspaceRoot, 'settings.json'),
        JSON.stringify({
          schemaVersion: 1,
          onboarding: {
            milestones: [
              { id: 'first_chat_sent', completedAt: 1 },
              { id: 'first_personalization', completedAt: 'bad' }, // invalid
              { id: 'first_chat_sent', skippedAt: 2 }, // last-wins
              { id: 'unknown_id', completedAt: 3 }, // invalid id
              { id: 'first_chat_sent', completedAt: 4, prompt: 'leak' }, // extra field
            ],
          },
        }),
      );
      const settings = await store.get();
      // After sanitize: first_chat_sent has skippedAt: 2 (last valid;
      // the 4-with-extra is rejected before it could overwrite).
      assert.equal(settings.onboarding.milestones.length, 1);
      assert.equal(settings.onboarding.milestones[0]?.id, 'first_chat_sent');
      assert.equal(settings.onboarding.milestones[0]?.skippedAt, 2);
      assert.equal(settings.onboarding.milestones[0]?.completedAt, undefined);
    } finally {
      await rm(workspaceRoot, { recursive: true, force: true });
    }
  });
});

describe('SettingsStore.clearOnboardingMilestone', () => {
  it('removes one milestone and preserves the rest', async () => {
    const workspaceRoot = await mkdtemp(join(tmpdir(), 'maka-settings-milestone-clear-'));
    try {
      const store = createSettingsStore(workspaceRoot);
      await store.upsertOnboardingMilestone('first_chat_sent', 'completed');
      await store.upsertOnboardingMilestone('first_run_suggestion_workspace_map', 'skipped');

      const after = await store.clearOnboardingMilestone('first_run_suggestion_workspace_map');

      assert.equal(
        after.some((entry) => entry.id === 'first_run_suggestion_workspace_map'),
        false,
      );
      assert.equal(
        after.some((entry) => entry.id === 'first_chat_sent'),
        true,
      );
    } finally {
      await rm(workspaceRoot, { recursive: true, force: true });
    }
  });

  it('rejects invalid milestone id (TypeScript-bypassing call)', async () => {
    const workspaceRoot = await mkdtemp(join(tmpdir(), 'maka-settings-milestone-clear-invalid-'));
    try {
      const store = createSettingsStore(workspaceRoot);
      await assert.rejects(
        () =>
          (store.clearOnboardingMilestone as unknown as (id: string) => Promise<unknown>).call(
            store,
            'not_a_milestone',
          ),
        /invalid onboarding milestone id/,
      );
    } finally {
      await rm(workspaceRoot, { recursive: true, force: true });
    }
  });
});

describe('SettingsStore.get file recovery', () => {
  it('serializes concurrent first reads while creating default settings', async () => {
    const workspaceRoot = await mkdtemp(join(tmpdir(), 'maka-settings-concurrent-defaults-'));
    const originalNow = Date.now;
    try {
      Date.now = () => 1_000;
      const store = createSettingsStore(workspaceRoot);

      const settings = await Promise.all(Array.from({ length: 16 }, () => store.get()));

      assert.equal(
        settings.every((value) => value.schemaVersion === 1),
        true,
      );
      const raw = await readFile(join(workspaceRoot, 'settings.json'), 'utf8');
      assert.equal(JSON.parse(raw).schemaVersion, 1);
    } finally {
      Date.now = originalNow;
      await rm(workspaceRoot, { recursive: true, force: true });
    }
  });

  it('creates defaults only when settings.json is missing', async () => {
    const workspaceRoot = await mkdtemp(join(tmpdir(), 'maka-settings-defaults-'));
    try {
      const store = createSettingsStore(workspaceRoot);

      const settings = await store.get();
      const raw = await readFile(join(workspaceRoot, 'settings.json'), 'utf8');

      assert.equal(settings.schemaVersion, 1);
      assert.match(raw, /"schemaVersion": 1/);
    } finally {
      await rm(workspaceRoot, { recursive: true, force: true });
    }
  });

  it('rejects corrupt settings.json without overwriting user settings bytes', async () => {
    const workspaceRoot = await mkdtemp(join(tmpdir(), 'maka-settings-corrupt-'));
    try {
      const store = createSettingsStore(workspaceRoot);
      const settingsPath = join(workspaceRoot, 'settings.json');
      const corrupt = '{"appearance":{"theme":"dark"}';
      await writeFile(settingsPath, corrupt, 'utf8');

      await assert.rejects(() => store.get(), SyntaxError);
      assert.equal(await readFile(settingsPath, 'utf8'), corrupt);
    } finally {
      await rm(workspaceRoot, { recursive: true, force: true });
    }
  });
});
